name: Build and Test

on:
  push:
    branches: [ '**' ]
    paths:
      - '.github/workflows/**'
      - 'main.go'
      - 'rcap/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install required packages
      run: |
        sudo apt update
        sudo apt install -y libpcap-dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...

    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
